export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    // Modulos y ambitos de la spec §1.1 + apps del monorepo.
    'scope-enum': [
      2,
      'always',
      [
        'api',
        'dfsa',
        'dfsm',
        'wafm',
        'landing',
        'schemas',
        'ui',
        'types',
        'config',
        'auth',
        'account',
        'subs',
        'susc',
        'schedule',
        'booking',
        'attendance',
        'members',
        'venues',
        'rooms',
        'products',
        'contracts',
        'billing',
        'training',
        'planning',
        'results',
        'rms',
        'health',
        'notifications',
        'feedback',
        'entitlements',
        'crm',
        'audit',
        'waivers',
        'metrics',
        'infra',
        'ci',
        'docs',
        'deps',
        'repo',
      ],
    ],
    'subject-case': [0],
    'header-max-length': [2, 'always', 100],
  },
};
